apiVersion: v1
kind: Pod
metadata: 
 name: volume_exercise
spec:
 containers:
 - name: app1 
   image: supergiantkir/animals:bear 
   ports: 
   - containerPort: 80
   volumeMounts:
   - name: app-storage
    mountPath: /storage

 - name: app2
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080
   volumeMounts:
   - name: app-storage
    mountPath: /storage

 volumes:
 - name: app-storage
   emptyDir: {}

